### ISSUE TITLE
Create proxy networks

### ISSUE THREAD

**Issue by gk-codes** [gk-codes/ansible-role-docker-traefik#1]
In the README.md it is mentioned that this role creates proxy networks, but as of now it does not.

They have to be created manually:

```bash
docker network create NETWORKNAME
```

The container's docker-compose.yml files need to be updated accordingly:

```bash
docker network connect NETWORKNAME CONTAINERNAME
```

```yaml
networks:
  NETWORKNAME:
    external: true
```

```yaml
services:
  app:
    networks:
      - NETWORKNAME
```
